// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvdyomzdgoavugcwhqfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2ZHlvbXpkZ29hdnVnY3docWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzE5MzIsImV4cCI6MjA3MzEwNzkzMn0.EWTXh1Z-4jLOm4QeZEH4wy3jpuYYUUeWQ1rqSpvZjVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});